### ISSUE TITLE
Just a question - not an issue

### ISSUE THREAD

**Issue by tedsmith** [ollydev/libTesseract#2]
Dear Olly

Thanks for the updated compilation of the Tesseract library to version 5, and the 32 and 64 bit DLL's. 

I wanted to ask if you knew how well they might work with the TTesseractOCR4 library for FreePascal, from [here](https://github.com/r1me/TTesseractOCR4). I ask with specific reference to Leptonica. Because that library, for reasons I am unclear about, requires both the Tesseract and Leptonica libraries and a load of these other cpan.demo....DLLs. It's so confusing. Suffice to say that if the library for Leptonica fails to load, then I can't use the library, even if the Tesseract library does load. So it seems somewhat reliant. Your solution looks like it wraps it all into one DLL (which is perfect!) but I'm unsure if it would work with that library? Do you think it would (before I go and re-code all my DLL lookups etc).

**Comment by ollydev** [comment]
That was annoying... Windows libs:
[artifact.zip](https://github.com/ollydev/libTesseract/files/6779434/artifact.zip)

TTesseractOCR4 seems to work:
```
$ ./lazarus_console_simple.exe
The (quick) [brown] {fox} jumps!
Over the $43,456.78 <lazy> #90 dog
& duck/goose, as 12.5% of E-mail
from aspammer@website.com is spam.
```

Changed the following in `tesseractocr.consts`
```
libtesseract = 'libtesseract64.dll';
libleptonica = libtesseract;
```
The libs are current tesseract master. If any headers changed from version 4 they will need to be updated.
For example  `GetTesseractProcAddress('TessBaseAPIRecognizeForChopTest')`  no longer exists, so I commented it out.

**Comment by ollydev** [comment]
New release: https://github.com/ollydev/libTesseract/releases/tag/4

**Comment by tedsmith** [comment]
This is AMAZING Olly! Thanks so much for this. I have tested it and, exactly as you describe and the few changes needed, this seems to work flawlessly! This has really driven my project forward! Thank you. 

Out of interest, just so I can perhaps compile the DLL's myself in the future, may I ask what the steps are? I saw your workflow yml file but if I wanted to compile this using MYSYS for Windows, for example (I only need it for Windows), are you able to walk through the steps needed? Or is there a doc that describes how to do it? Because having these two single DLLs is 1000 times better and easier than via the other method.

**Comment by ollydev** [comment]
The action uses MSYS2 on windows: https://github.com/ollydev/libTesseract/blob/master/.github/workflows/build.yml#L139
It should be easy to copy locally, or you can even fork this repo and make changes.

The TLDR is:
- clone tesseract
- move sw.cpp into tesseract clone
- build tesseract using sw https://github.com/SoftwareNetwork/binaries
- extract libs we need from sw (the python script in the workflow)
- and build our plugin using cmake

All done in MSYS2 shell.
